### PR TITLE
Server.charshes.issue

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@joshuawilson I've noticed GH user without emails where causing trouble. ie: make the server crashes, pod then restart => 502 by the admin proxy
I think now we should be good to go with that fix. once merged you can test on prod-preview.

**Comment by joshuawilson** [comment]
I have an email associated with my github user. Where are you seeing the missing email?

**Comment by corinnekrych** [comment]
@joshuawilson non-public ie: visible email
screenshot 2018-03-07 08 52 58_preview
vs
screenshot 2018-03-07 08 53 32_preview

**Comment by joshuawilson** [comment]
@corinnekrych I don't know what is going on. I have my email on my profile and it is public. I've had it that way for more then a year. I don't know why I don't see it when I look at my profile but it is there when I edit it.

**Comment by corinnekrych** [comment]
@joshuawilson I'm confident the edit I made will fix your issue (and anyway will fix any other account without email and prevent server from crahsing). Let's wait for @xcoulon review and then we can merge it and try it on prod-preview. 
I've also added more CI/CD check to catch those JS runtime issues (some lint, and looking for Js test too).

**Comment by joshuawilson** [comment]
sounds good

**Pull request merged**
